/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppHoldingsRouteImport } from './routes/_app.holdings'
import { Route as AppMarketDataEodRouteImport } from './routes/_app.market-data-eod'
import { Route as AppMarketDataEodBackfillRouteImport } from './routes/_app.market-data-eod-backfill'
import { Route as AppMarketDataEodPilotRouteImport } from './routes/_app.market-data-eod-pilot'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTransactionsRouteImport } from './routes/_app.transactions'
import { Route as AppImportIndexRouteImport } from './routes/_app.import.index'
import { Route as AppImportBatchIdRouteImport } from './routes/_app.import.$batchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHoldingsRoute = AppHoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketDataEodRoute = AppMarketDataEodRouteImport.update({
  id: '/market-data-eod',
  path: '/market-data-eod',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketDataEodBackfillRoute =
  AppMarketDataEodBackfillRouteImport.update({
    id: '/market-data-eod-backfill',
    path: '/market-data-eod-backfill',
    getParentRoute: () => AppRoute,
  } as any)
const AppMarketDataEodPilotRoute = AppMarketDataEodPilotRouteImport.update({
  id: '/market-data-eod-pilot',
  path: '/market-data-eod-pilot',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppImportIndexRoute = AppImportIndexRouteImport.update({
  id: '/import/',
  path: '/import/',
  getParentRoute: () => AppRoute,
} as any)
const AppImportBatchIdRoute = AppImportBatchIdRouteImport.update({
  id: '/import/$batchId',
  path: '/import/$batchId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/holdings': typeof AppHoldingsRoute
  '/market-data-eod': typeof AppMarketDataEodRoute
  '/market-data-eod-backfill': typeof AppMarketDataEodBackfillRoute
  '/market-data-eod-pilot': typeof AppMarketDataEodPilotRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/import/$batchId': typeof AppImportBatchIdRoute
  '/import/': typeof AppImportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/holdings': typeof AppHoldingsRoute
  '/market-data-eod': typeof AppMarketDataEodRoute
  '/market-data-eod-backfill': typeof AppMarketDataEodBackfillRoute
  '/market-data-eod-pilot': typeof AppMarketDataEodPilotRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/import/$batchId': typeof AppImportBatchIdRoute
  '/import': typeof AppImportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/holdings': typeof AppHoldingsRoute
  '/_app/market-data-eod': typeof AppMarketDataEodRoute
  '/_app/market-data-eod-backfill': typeof AppMarketDataEodBackfillRoute
  '/_app/market-data-eod-pilot': typeof AppMarketDataEodPilotRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/import/$batchId': typeof AppImportBatchIdRoute
  '/_app/import/': typeof AppImportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/holdings'
    | '/market-data-eod'
    | '/market-data-eod-backfill'
    | '/market-data-eod-pilot'
    | '/settings'
    | '/transactions'
    | '/import/$batchId'
    | '/import/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/holdings'
    | '/market-data-eod'
    | '/market-data-eod-backfill'
    | '/market-data-eod-pilot'
    | '/settings'
    | '/transactions'
    | '/import/$batchId'
    | '/import'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/dashboard'
    | '/_app/holdings'
    | '/_app/market-data-eod'
    | '/_app/market-data-eod-backfill'
    | '/_app/market-data-eod-pilot'
    | '/_app/settings'
    | '/_app/transactions'
    | '/_app/import/$batchId'
    | '/_app/import/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/holdings': {
      id: '/_app/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof AppHoldingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/market-data-eod': {
      id: '/_app/market-data-eod'
      path: '/market-data-eod'
      fullPath: '/market-data-eod'
      preLoaderRoute: typeof AppMarketDataEodRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/market-data-eod-backfill': {
      id: '/_app/market-data-eod-backfill'
      path: '/market-data-eod-backfill'
      fullPath: '/market-data-eod-backfill'
      preLoaderRoute: typeof AppMarketDataEodBackfillRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/market-data-eod-pilot': {
      id: '/_app/market-data-eod-pilot'
      path: '/market-data-eod-pilot'
      fullPath: '/market-data-eod-pilot'
      preLoaderRoute: typeof AppMarketDataEodPilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import/': {
      id: '/_app/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof AppImportIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import/$batchId': {
      id: '/_app/import/$batchId'
      path: '/import/$batchId'
      fullPath: '/import/$batchId'
      preLoaderRoute: typeof AppImportBatchIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppHoldingsRoute: typeof AppHoldingsRoute
  AppMarketDataEodRoute: typeof AppMarketDataEodRoute
  AppMarketDataEodBackfillRoute: typeof AppMarketDataEodBackfillRoute
  AppMarketDataEodPilotRoute: typeof AppMarketDataEodPilotRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppImportBatchIdRoute: typeof AppImportBatchIdRoute
  AppImportIndexRoute: typeof AppImportIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppHoldingsRoute: AppHoldingsRoute,
  AppMarketDataEodRoute: AppMarketDataEodRoute,
  AppMarketDataEodBackfillRoute: AppMarketDataEodBackfillRoute,
  AppMarketDataEodPilotRoute: AppMarketDataEodPilotRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppImportBatchIdRoute: AppImportBatchIdRoute,
  AppImportIndexRoute: AppImportIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
